# Using Local Docker infrastructure
pipeline:
  name: yaswanth
  identifier: yaswanth
  projectIdentifier: HarnessCICDZerotoHero
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          infrastructure:
            type: LocalDocker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    image: maven:3.9-eclipse-temurin-17
                    command: |
                      echo "=== Hello from Harness CI/CD! ==="
                      echo "Pipeline is running on Local Docker"
                      echo "=== Success! ==="
  properties:
    ci:
      codebase:
        connectorRef: account.HarnessCICDZerotoHero
        repoName: Harness-CI-CD-Zero-to-Hero
        build: <+input>
