# Pipeline 2: Using KUBERNETES (VM Pool with Delegate)
# Use this when: You have a Delegate installed with VM pool
pipeline:
  name: yaswanth
  identifier: yaswanth
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: yaswanth
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |
                      echo "=== Building Hello World ==="
                      mvn clean package -q
                      echo ""
                      echo "=== Running the App ==="
                      java -jar target/hello-world-1.0.0.jar
                      echo ""
                      echo "=== Pipeline Success! ==="
  properties:
    ci:
      codebase:
        connectorRef: HarnessCICDZerotoHero
        repoName: Harness-CI-CD-Zero-to-Hero
        build: <+input>
